name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@9df63075f032b16ffdea51a7c9324c67c155820a # main
    secrets: inherit
