name: Publish

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@a505980d2bca72e881e343132d943b03e79f1e62 # main
    secrets: inherit
