name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    uses: h13/.github/.github/workflows/publish-node.yml@027e68677754001ca07ed3f800899d3ec4e29f70 # v1
    secrets: inherit
